import { auth } from "@/auth";
import { buildOfflineAssetPackage } from "@/data/offline-export";
import { authenticateBoatDevice,type BoatPermission } from "@/data/boat-device-auth";
import { persistOfflineLogBatchForOwner,type OfflineLogUploadBatch } from "@/data/offline-log-sync";
export const dynamic="force-dynamic";
function noStore(body:unknown,init:ResponseInit={}){return Response.json(body,{...init,headers:{...init.headers,"Cache-Control":"private, no-store"}})}
async function authenticatedUserId(){const session=await auth();return session?.user?.id||null}
async function principal(request:Request,assetId:string,permission:BoatPermission){const userId=await authenticatedUserId();if(userId)return{ownerId:userId,kind:"user" as const,deviceId:null};const device=await authenticateBoatDevice(request.headers.get("authorization"),assetId,permission);return device?{ownerId:device.ownerId,kind:"device" as const,deviceId:device.deviceId}:null}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,p=await principal(request,id,"snapshot:read");if(!p)return noStore({ok:false,authenticated:false,error:"Authentication required for offline sync."},{status:401});const offlinePackage=await buildOfflineAssetPackage(id,p.ownerId);if(!offlinePackage)return noStore({ok:false,authenticated:true,error:"Asset not found or not authorized."},{status:404});const url=new URL(request.url),localRevision=url.searchParams.get("revision"),sync=offlinePackage.sync,authKind=p.kind;if(localRevision&&sync?.packageRevision&&localRevision===sync.packageRevision)return noStore({ok:true,authenticated:true,authKind,status:"current",sync,package:null});return noStore({ok:true,authenticated:true,authKind,status:"update",sync,package:offlinePackage})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,p=await principal(request,id,"operating-log:write");if(!p)return noStore({ok:false,authenticated:false,uploadEnabled:false,error:"Authentication with operating-log write permission is required."},{status:401});if(process.env.ERNEST_OFFLINE_LOG_UPLOAD_ENABLED!=="true")return noStore({ok:false,authenticated:true,authKind:p.kind,uploadEnabled:false,error:"Boat-to-Cloud operating-log upload is not enabled."},{status:503});try{const body=await request.json() as OfflineLogUploadBatch,result=await persistOfflineLogBatchForOwner(body,id,p.ownerId);return noStore({ok:true,authenticated:true,authKind:p.kind,uploadEnabled:true,...result})}catch(error){return noStore({ok:false,authenticated:true,authKind:p.kind,uploadEnabled:true,error:error instanceof Error?error.message:"Offline log upload failed."},{status:400})}}
