import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { buildOfflineAssetPackage } from "@/data/offline-export";
import { persistOfflineLogBatchForOwner,type OfflineLogUploadBatch } from "@/data/offline-log-sync";
export const dynamic="force-dynamic";
function noStore(body:unknown,init:ResponseInit={}){return Response.json(body,{...init,headers:{...init.headers,"Cache-Control":"private, no-store"}})}
async function authenticatedUserId(){const session=await auth();return session?.user?.id||null}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,userId=await authenticatedUserId();if(!userId)return noStore({ok:false,authenticated:false,error:"Authentication required for offline sync."},{status:401});const offlinePackage=await buildOfflineAssetPackage(id,userId);if(!offlinePackage)notFound();const url=new URL(request.url),localRevision=url.searchParams.get("revision"),sync=offlinePackage.sync;if(localRevision&&sync?.packageRevision&&localRevision===sync.packageRevision)return noStore({ok:true,authenticated:true,status:"current",sync,package:null});return noStore({ok:true,authenticated:true,status:"update",sync,package:offlinePackage})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,userId=await authenticatedUserId();if(!userId)return noStore({ok:false,authenticated:false,uploadEnabled:false,error:"Authentication required for offline sync."},{status:401});if(process.env.ERNEST_OFFLINE_LOG_UPLOAD_ENABLED!=="true")return noStore({ok:false,authenticated:true,uploadEnabled:false,error:"Boat-to-Cloud operating-log upload is not enabled."},{status:503});try{const body=await request.json() as OfflineLogUploadBatch,result=await persistOfflineLogBatchForOwner(body,id,userId);return noStore({ok:true,authenticated:true,uploadEnabled:true,...result})}catch(error){return noStore({ok:false,authenticated:true,uploadEnabled:true,error:error instanceof Error?error.message:"Offline log upload failed."},{status:400})}}
