"use server";
import { auth } from "@/auth";
import { answerErnestQuestion } from "@/data/ask-ernest";
import { getAsset } from "@/data/assets";
import { getErnestDocumentContext } from "@/data/document-context";
import { proposeErnestWrite,type ErnestWriteProposal } from "@/data/ernest-write-proposals";
import { getComponentLifecycles } from "@/data/equipment-knowledge";
import { getInventoryItems,getInventoryLocations } from "@/data/inventory";
import { getLogEntries } from "@/data/log-entries";
import { getProcedures } from "@/data/procedures";
export type AskErnestState={question:string;answer:string;sources:{documentTitle:string;pageNumber:number}[];proposal?:ErnestWriteProposal;error?:string};
const empty=():AskErnestState=>({question:"",answer:"",sources:[]});
function tokens(q:string){const stop=new Set(["a","an","and","are","do","does","for","have","i","in","is","it","me","my","of","on","the","to","what","where","which","with"]);return Array.from(new Set(q.toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(t=>t.length>=2&&!stop.has(t))));}
function relevant(q:string,items:Awaited<ReturnType<typeof getInventoryItems>>){const ts=tokens(q);return items.map(item=>{const n=item.name.toLowerCase(),d=(item.details??"").toLowerCase(),l=item.locations.join(" ").toLowerCase();let score=0;for(const t of ts){if(n.includes(t))score+=4;if(d.includes(t))score+=2;if(l.split(/\s+/).includes(t))score+=3;}if(ts.length&&ts.every(t=>n.includes(t)))score+=8;return{item,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.item.name.localeCompare(b.item.name)).slice(0,12).map(x=>x.item);}
function invLine(i:Awaited<ReturnType<typeof getInventoryItems>>[number]){return `- ${[i.name,i.locations.length?`storage location code ${i.locations.join(", ")}`:"storage location not recorded",i.quantity?`quantity ${i.quantity}`:"",i.details?`details: ${i.details}`:""].filter(Boolean).join(" · ")}`;}
function verified(asset:NonNullable<Awaited<ReturnType<typeof getAsset>>>,logs:Awaited<ReturnType<typeof getLogEntries>>,inventory:Awaited<ReturnType<typeof getInventoryItems>>,q:string){const lines=["ASSET RECORD:",`Name: ${asset.name}`,`Type: ${asset.type}`,asset.make?`Make: ${asset.make}`:"",asset.model?`Model: ${asset.model}`:"",asset.year?`Year: ${asset.year}`:"",asset.registrationNumber?`Registration / VIN: ${asset.registrationNumber}`:"",asset.summary?`Summary: ${asset.summary}`:""].filter(Boolean);for(const s of asset.systems){lines.push(`\nSYSTEM: ${s.name}`);if(s.description)lines.push(`Description: ${s.description}`);for(const c of s.components){lines.push(`Component: ${c.name}`);if(c.manufacturer)lines.push(`Manufacturer: ${c.manufacturer}`);if(c.model)lines.push(`Model: ${c.model}`);if(c.serialNumber)lines.push(`Serial number: ${c.serialNumber}`);if(c.location)lines.push(`Location: ${c.location}`);if(c.notes)lines.push(`Notes: ${c.notes}`);}}if(inventory.length){const matches=relevant(q,inventory);if(matches.length){lines.push("\nRELEVANT VERIFIED INVENTORY MATCHES:","Location codes are the owner's exact storage-location codes.");for(const i of matches)lines.push(invLine(i));}lines.push("\nVERIFIED INVENTORY:");for(const i of inventory)lines.push(invLine(i));}const recent=logs.slice(0,20);if(recent.length){lines.push("\nRECENT OPERATING LOG:");for(const l of recent)lines.push(`[${l.occurredAt.toISOString().slice(0,10)}] ${l.entryType}: ${l.title} — ${l.body}`);}return lines.join("\n");}
function proposalAnswer(p:ErnestWriteProposal){
  if(p.kind==="log")return `I can save that to ${p.log.entryType} history for ${p.log.occurredAt}. Review it below before I write anything.`;
  if(p.kind==="component_fact")return `I can update ${p.componentFact.componentName}. Review the proposed change below first.`;
  if(p.kind==="component_lifecycle")return `I can change the lifecycle status for ${p.lifecycle.componentName}. Review it below before I write anything.`;
  if(p.kind==="inventory_add")return `I can add ${p.inventory.name} to onboard inventory. Review it below before I write anything.`;
  if(p.kind==="inventory_update")return `I can update ${p.inventory.currentName} in onboard inventory. Review the change below first.`;
  if(p.kind==="procedure_add")return `I can add ${p.procedure.title}. Review every proposed step below before I save it.`;
  if(p.kind==="procedure_update")return `I can update ${p.procedure.currentTitle}. Review the complete resulting procedure below before I save it.`;
  return "I can save that as owner-provided information for this asset. Review the change below first.";
}
export async function askErnest(assetId:string,_previous:AskErnestState,formData:FormData):Promise<AskErnestState>{const session=await auth();if(!session?.user?.id)return{...empty(),error:"Please sign in again."};const question=String(formData.get("question")??"").trim().slice(0,500);if(!question)return{...empty(),error:"Enter a question."};const conversation=String(formData.get("conversation")??"").trim().slice(-6000);const thinkHarder=String(formData.get("thinkHarder")??"")==="true";try{const[asset,logs,inventory,locations,lifecycles,procedures,context]=await Promise.all([getAsset(assetId,session.user.id),getLogEntries(assetId,session.user.id),getInventoryItems(assetId,session.user.id),getInventoryLocations(assetId,session.user.id),getComponentLifecycles(assetId,session.user.id),getProcedures(assetId,session.user.id),getErnestDocumentContext(assetId,session.user.id,question)]);if(!asset)return{...empty(),question,error:"I couldn’t find that asset."};const proposal=await proposeErnestWrite(question,asset,inventory,locations,conversation,lifecycles,procedures);if(proposal)return{question,answer:proposalAnswer(proposal),sources:[],proposal};const contextualQuestion=conversation?`Recent conversation (context only, not verified evidence):\n${conversation}\n\nCurrent question:\n${question}`:question;const answer=await answerErnestQuestion(contextualQuestion,context,verified(asset,logs,inventory,question),thinkHarder);const seen=new Set<string>();const sources=context.filter(p=>{const k=`${p.documentId}:${p.pageNumber}`;if(seen.has(k))return false;seen.add(k);return true;}).map(p=>({documentTitle:p.documentTitle,pageNumber:p.pageNumber}));return{question,answer,sources};}catch(error){console.error("Ask Ernest failure",error);return{question,answer:"",sources:[],error:"Ernest couldn’t answer that right now. Please try again."};}}
