import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { auth } from "@/auth";
import { AssetAppHeader } from "@/components/asset-app-header";
import { ErrorNotice } from "@/components/error-notice";
import { SystemDeleteButton } from "@/components/system-delete-button";
import { getAsset } from "@/data/assets";
import { getLogEntries } from "@/data/log-entries";
import { logEntryTypes } from "@/domain/log-entries";
import { addLogEntry } from "./actions";
import { addSystem, editSystem, removeSystem } from "./inventory-actions";

export const dynamic="force-dynamic";

export default async function AssetDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{inventoryError?:string}>}){
  const{id}=await params;const{inventoryError}=await searchParams;const session=await auth();if(!session?.user?.id)redirect("/sign-in");const asset=await getAsset(id,session.user.id);if(!asset)notFound();const logEntries=await getLogEntries(id,session.user.id);const createEntry=addLogEntry.bind(null,id);const componentCount=asset.systems.reduce((total,system)=>total+system.components.length,0);
  return <div className="app-shell"><AssetAppHeader assetId={id} assetName={asset.name} email={session.user.email}/><main className="page-wrap detail-wrap"><section className="page-heading compact-page-heading"><p className="eyebrow">Asset setup</p><h1>{asset.name}</h1><p className="lede">{[asset.year,asset.make,asset.model].filter(Boolean).join(" ")} · {asset.type}</p><div className="record-action-row"><Link className="primary-button" href={`/assets/${asset.id}/edit`}>Edit asset identity</Link><Link className="secondary-button" href={`/assets/${asset.id}/knowledge`}>Manage equipment</Link></div></section>

<section className="systems-section"><div className="section-heading"><h2>Asset facts</h2><p>Owner-controlled identity used throughout Ernest.</p></div><dl className="asset-facts setup-facts"><div><dt>Make</dt><dd>{asset.make||"—"}</dd></div><div><dt>Model</dt><dd>{asset.model||"—"}</dd></div><div><dt>Year</dt><dd>{asset.year||"—"}</dd></div>{asset.registrationNumber?<div><dt>Registration / VIN</dt><dd>{asset.registrationNumber}</dd></div>:null}</dl>{asset.summary?<p className="asset-summary" style={{marginTop:"1rem"}}>{asset.summary}</p>:null}</section>

<section className="log-section"><div className="section-heading"><h2>Operating log</h2><p>{logEntries.length} {logEntries.length===1?"entry":"entries"}. You can also record ordinary updates through Chat.</p></div><div className="log-layout"><form className="log-form" action={createEntry}><h3>Add log entry</h3><label>Occurred at<input name="occurredAt" type="datetime-local" required/></label><label>Entry type<select name="entryType" defaultValue="note">{logEntryTypes.map(type=><option key={type} value={type}>{type}</option>)}</select></label><label>Title<input name="title" maxLength={200} required/></label><label>Body<textarea name="body" rows={5} required/></label><div className="coordinate-fields"><label>Latitude <span>(optional)</span><input name="latitude" type="number" min="-90" max="90" step="any"/></label><label>Longitude <span>(optional)</span><input name="longitude" type="number" min="-180" max="180" step="any"/></label></div><button type="submit">Add log entry</button></form><div className="log-list">{logEntries.length===0?<p className="empty-log">No log entries yet.</p>:logEntries.map(entry=><article className="log-entry" key={entry.id}><div className="log-entry-meta"><span>{entry.entryType}</span><time dateTime={entry.occurredAt.toISOString()}>{entry.occurredAt.toLocaleString()}</time></div><h3>{entry.title}</h3><p>{entry.body}</p>{entry.latitude!==undefined&&entry.longitude!==undefined?<small>{entry.latitude}, {entry.longitude}</small>:null}</article>)}</div></div></section>

<section className="systems-section"><div className="section-heading"><h2>System structure</h2><p>{asset.systems.length} systems · {componentCount} equipment records. Systems organize equipment; individual equipment is managed on the Equipment screen or through Chat.</p></div><ErrorNotice message={inventoryError}/><details className="record-editor"><summary>Add system</summary><div className="record-editor-panel"><form className="compact-form" action={addSystem.bind(null,id)}><label>Name<input name="name" maxLength={100} required/></label><label>Description<textarea name="description" maxLength={500}/></label><button className="primary-button" type="submit">Add system</button></form></div></details><div className="system-list">{asset.systems.map(system=><article className="system-card" key={system.id}><div className="system-heading"><div><h3>{system.name}</h3><p>{system.description}</p></div><span>{system.components.length} equipment</span></div><div className="setup-system-actions"><Link className="secondary-button" href={`/assets/${id}/knowledge?system=${encodeURIComponent(system.id)}`}>View equipment</Link><details className="record-editor"><summary>Edit system</summary><div className="record-editor-panel"><form className="compact-form" action={editSystem.bind(null,id,system.id)}><label>Name<input name="name" defaultValue={system.name} maxLength={100} required/></label><label>Description<textarea name="description" defaultValue={system.description} maxLength={500}/></label><button className="primary-button" type="submit">Save system</button></form><div className="danger-zone"><strong>Permanent deletion</strong><p>Deleting a system also deletes the equipment records inside it. Use only for setup mistakes.</p><form action={removeSystem.bind(null,id,system.id)}><SystemDeleteButton name={system.name}/></form></div></div></details></div></article>)}</div></section></main></div>;
}
