import { notFound, redirect } from "next/navigation";

import { auth } from "@/auth";
import { AssetAppHeader } from "@/components/asset-app-header";
import { PhotoUploadPanel } from "@/components/photo-upload-panel";
import { getAsset } from "@/data/assets";
import { listPhotos } from "@/data/photos";
import { deletePhotoAction, updatePhotoAction } from "../photo-actions";

export const dynamic = "force-dynamic";
function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/(1024*1024)).toFixed(1)} MB`;}

export default async function PhotosPage({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<{saved?:string}>}){
  const{id}=await params;const query=searchParams?await searchParams:undefined;const session=await auth();if(!session?.user?.id)redirect("/sign-in");const asset=await getAsset(id,session.user.id);if(!asset)notFound();const photos=await listPhotos(id,session.user.id);const components=asset.systems.flatMap(system=>system.components.map(component=>({id:component.id,label:`${system.name} · ${component.name}`})));const savedMessage=query?.saved==="updated"?"✓ Photo details saved.":query?.saved==="deleted"?"✓ Photo deleted.":undefined;
  return <div className="app-shell"><AssetAppHeader assetId={id} assetName={asset.name} email={session.user.email}/><main className="page-wrap detail-wrap"><section className="page-heading compact-page-heading"><p className="eyebrow">Evidence · {asset.name}</p><h1>Photos</h1><p className="lede">Private visual evidence. Upload first; add context only when you know it.</p></section>{savedMessage?<p className="operation-status" role="status">{savedMessage}</p>:null}<PhotoUploadPanel assetId={id}/><section className="systems-section"><div className="section-heading"><h2>Photo library</h2><p>{photos.length} photo{photos.length===1?"":"s"} · {photos.filter(p=>p.componentId).length} linked to equipment.</p></div>{photos.length===0?<p className="empty-log">No photos yet.</p>:<div className="photo-evidence-grid">{photos.map(photo=><article className="photo-evidence-card" key={photo.id}><a className="photo-evidence-preview" href={`/assets/${id}/photos/${photo.id}/original`} target="_blank" rel="noreferrer">{photo.contentType==="image/heic"||photo.contentType==="image/heif"?<div className="photo-format-placeholder">HEIC<br/><small>Open original</small></div>:<img src={`/assets/${id}/photos/${photo.id}/original`} alt={photo.title} loading="lazy"/>}</a><div className="photo-evidence-body"><div className="log-entry-meta"><span>{photo.contentType.replace("image/","").toUpperCase()}</span><span>{formatBytes(photo.sizeBytes)}</span></div><h3>{photo.title}</h3><p className="asset-summary">{photo.originalFilename}</p><div className="record-action-row"><a className="secondary-button" href={`/assets/${id}/photos/${photo.id}/original`} target="_blank" rel="noreferrer">Open original ↗</a><details className="record-editor"><summary>Edit photo</summary><div className="record-editor-panel"><form className="compact-form" action={updatePhotoAction.bind(null,id,photo.id)}><label>Title<input name="title" defaultValue={photo.title} maxLength={200} required/></label><label>Equipment association<select name="componentId" defaultValue={photo.componentId??""}><option value="">Not linked</option>{components.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>Notes<textarea name="notes" defaultValue={photo.notes??""} rows={4} placeholder="What this shows, where it is, why it matters…"/></label><button className="primary-button" type="submit">Save photo details</button></form><div className="danger-zone"><strong>Permanent deletion</strong><p>Delete only photos you do not want retained as evidence.</p><details><summary>Delete photo…</summary><form action={deletePhotoAction.bind(null,id,photo.id)}><button className="delete-button" type="submit">Delete photo permanently</button></form></details></div></div></details></div></div></article>)}</div>}</section></main></div>;
}
