import { notFound, redirect } from "next/navigation";

import { auth } from "@/auth";
import { AssetAppHeader } from "@/components/asset-app-header";
import { getAsset } from "@/data/assets";
import { getDocumentForAsset, getDocumentPages } from "@/data/documents";
import { getMaintenanceCandidates, getMaintenanceGuidance } from "@/data/maintenance-candidates";
import { removeDocument, renameDocument } from "../../document-actions";
import { approveMaintenanceCandidate, editAndApproveMaintenanceCandidate, generateMaintenanceCandidates, rejectMaintenanceCandidate } from "./maintenance-actions";

export const dynamic="force-dynamic";
function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/(1024*1024)).toFixed(1)} MB`;}
function extractionQuality(text:string){const n=(text.replace(/\s+/g," ").trim().match(/[A-Za-z0-9]/g)??[]).length;if(n===0)return{label:"No text",weak:true};if(n<80)return{label:"Weak",weak:true};return{label:"Good",weak:false};}

export default async function DocumentDetailPage({params,searchParams}:{params:Promise<{id:string;documentId:string}>;searchParams:Promise<{saved?:string}>}){
  const{id,documentId}=await params;const query=await searchParams;const session=await auth();if(!session?.user?.id)redirect("/sign-in");const asset=await getAsset(id,session.user.id);if(!asset)notFound();const document=await getDocumentForAsset(documentId,id,session.user.id);if(!document)notFound();const pages=await getDocumentPages(documentId,id,session.user.id)??[];const[candidates,guidance]=await Promise.all([getMaintenanceCandidates(documentId,id,session.user.id),getMaintenanceGuidance(documentId,id,session.user.id)]);const pageQuality=pages.map(page=>({...page,quality:extractionQuality(page.text)}));const weakPages=pageQuality.filter(page=>page.quality.weak).length;const pendingCount=candidates.filter(c=>c.status==="pending").length;
  return <div className="app-shell"><AssetAppHeader assetId={id} assetName={asset.name} email={session.user.email}/><main className="page-wrap detail-wrap"><section className="page-heading compact-page-heading"><p className="eyebrow">Document · {asset.name}</p><h1>{document.title}</h1><p className="lede">{document.originalFilename} · {formatBytes(document.sizeBytes)} · {document.pageCount??"—"} pages</p></section>{query.saved==="title"?<p className="write-result success" role="status">✓ Document title saved.</p>:null}<div className="record-action-row"><a className="secondary-button" href={`/assets/${id}/documents/${documentId}/original`} target="_blank" rel="noreferrer">Open preserved original PDF ↗</a>{document.sourceUrl?<a className="secondary-button" href={document.sourceUrl} target="_blank" rel="noreferrer">Original web source ↗</a>:null}</div>

<section className="systems-section"><div className="section-heading"><h2>Document controls</h2><p>{document.extractionError?"Needs attention":document.extractedAt?"Ready for search and evidence":"Preserved in the vault; processing is optional until needed."}</p></div><div className="log-layout"><form className="compact-form" action={renameDocument.bind(null,id,documentId)}><h3>Title</h3><label>Document title<input name="title" defaultValue={document.title} maxLength={200} required/></label><button className="primary-button">Save title</button></form><div className="compact-form"><h3>Text processing</h3>{document.extractedAt?<p>Last extracted {document.extractedAt.toLocaleString()}.</p>:<p>Not processed yet.</p>}{document.extractedAt&&weakPages>0?<p className="error-notice">{weakPages} page{weakPages===1?"":"s"} still have weak or no readable text.</p>:null}{document.extractionError?<p className="error-notice">{document.extractionError}</p>:null}<form action={`/assets/${encodeURIComponent(id)}/documents/${encodeURIComponent(documentId)}/extract`} method="post"><button className="primary-button">{document.extractedAt?"Re-extract text":"Extract text"}</button></form></div></div><div className="danger-zone"><strong>Permanent deletion</strong><p>This removes the private PDF, extracted pages, and search chunks. It cannot be undone.</p><details><summary>Delete document…</summary><form action={removeDocument.bind(null,id,documentId)}><button className="delete-button">Delete document permanently</button></form></details></div></section>

<section className="systems-section"><div className="section-heading"><h2>Maintenance evidence</h2><p>Structured events remain optional proposals tied to the source page until you approve them.</p></div><details className="record-editor"><summary>Structured maintenance suggestions{pendingCount?` · ${pendingCount} awaiting review`:""}</summary><div className="record-editor-panel"><form className="compact-form" action={generateMaintenanceCandidates.bind(null,id,documentId)}><label>Interpretation guidance<textarea name="guidance" defaultValue={guidance} maxLength={2000} rows={3} placeholder={'Example: Dates are written Month/Year. “Sep 18” means September 2018.'}/></label><button className="primary-button" disabled={pages.length===0}>{candidates.length?"Regenerate pending suggestions":"Suggest structured events"}</button></form>{candidates.length?<div className="log-list">{candidates.map(c=><article className="log-entry" key={c.id}><div className="log-entry-meta"><span>PAGE {c.pageNumber}</span><span>{c.status.toUpperCase()}</span></div><h3>{c.action}</h3><p>{[c.dateText||c.occurredOn,c.engineHours?`${c.engineHours} engine hrs`:null].filter(Boolean).join(" · ")||"Date / hours not stated"}</p>{c.partsConsumables?<p><strong>Parts / consumables:</strong> {c.partsConsumables}</p>:null}{c.notes?<p><strong>Notes:</strong> {c.notes}</p>:null}<p className="asset-summary">Evidence: {document.title}, p. {c.pageNumber}</p>{c.status==="pending"?<div className="candidate-actions"><form action={approveMaintenanceCandidate.bind(null,id,documentId,c.id)}><button className="primary-button">Approve</button></form><details className="record-editor"><summary>Edit before approving</summary><div className="record-editor-panel"><form className="compact-form" action={editAndApproveMaintenanceCandidate.bind(null,id,documentId,c.id)}><label>Date as written<input name="dateText" defaultValue={c.dateText??""}/></label><label>Exact date, only if known<input name="occurredOn" type="date" defaultValue={c.occurredOn??""}/></label><label>Engine hours<input name="engineHours" inputMode="decimal" defaultValue={c.engineHours??""}/></label><label>Action<input name="action" defaultValue={c.action} required/></label><label>Parts / consumables<textarea name="partsConsumables" rows={2} defaultValue={c.partsConsumables??""}/></label><label>Notes<textarea name="notes" rows={2} defaultValue={c.notes??""}/></label><button className="primary-button">Save & approve</button></form></div></details><form action={rejectMaintenanceCandidate.bind(null,id,documentId,c.id)}><button className="delete-button">Reject</button></form></div>:null}</article>)}</div>:<p className="empty-log">No structured suggestions. Ernest can still use the document evidence directly.</p>}</div></details></section>

<section className="systems-section"><div className="section-heading"><h2>Extracted text</h2><p>{pages.length} pages · {weakPages} weak after OCR fallback.</p></div>{pages.length===0?<p className="empty-log">No extracted text yet.</p>:<div className="log-list">{pageQuality.map(page=><article className="log-entry" key={page.pageNumber}><div className="log-entry-meta"><span>PAGE {page.pageNumber}</span><span>{page.quality.label}</span></div>{page.text.trim()?<pre className="document-text-page">{page.text}</pre>:<p className="empty-log">No readable text recovered from this page.</p>}</article>)}</div>}</section></main></div>;
}
